spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_library
    username: postgres
    password: Gas01fer02edv
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    show-sql: true
